---
title: "Lab4: Procedimiento"
author: "Luz Arevalo"
date: "2022-09-01"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(highcharter)
library(plotly)
library(plyr)
library(dplyr)
library(openxlsx)
knitr::opts_chunk$set(echo = TRUE)
```


# Hallazgos
``` {r}
df <- read.csv('tabla_completa.csv')

## Unidades al mes
dfcantidad <- df %>%
  select(MES, CANTIDAD) %>%
  group_by(MES) %>%
  dplyr::summarise(unidades_totales = sum(CANTIDAD))


## Viajes mensuales por piloto
dfpilotos <- df %>%
  select(MES, PILOTO, COD_VIAJE) %>%
  group_by(MES) %>%
  dplyr::summarise(viajes = n_distinct(COD_VIAJE)/n_distinct(PILOTO))


## Política de crédito
dfcreditos <- df %>%
  select(MES, CLIENTE, CANTIDAD, CREDITO)

 dfcreditos%>%
  hchart("scatter", hcaes(x= CREDITO, y = CANTIDAD)) %>%
  hc_title(text = "<b>Política de crédito<b>")

```


# Tabla de costos
``` {r}
tarifas <- data.frame(COD_UNIDAD = c(1001,1002,1003),
                      UNIDAD= c("Camion grande", "Camion pequeño", "Panel"),
                      EXISTENCIAS = c(3,2,1),
                      VIAJES_MES = c(40,65,85),
                      PILOTO_V = c(125,75,50),
                      COMBUSTIBLE_U = c(0.05,0.05,0.05),
                      PRECIO_U = c(0.25,0.25,0.25),
                      CAPACIDAD_MAX = c(2500,1000,500))
```


# Proyección de la demanda
```{r message=FALSE, warning=FALSE}
demanda <- df %>% 
  select(MES,CLIENTE, CANTIDAD) %>% 
  group_by(MES, CLIENTE,CANTIDAD) %>%
  dplyr::summarise(proyeccion = CANTIDAD*1.2,
                   pedido = sum(CANTIDAD)*1.2/n(),
                   COD_UNIDAD = if (((sum(CANTIDAD)*1.2)/n())>=1000) {
                     COD_UNIDAD = 1001
                   } else {if(((sum(CANTIDAD)*1.2)/n())>=500){
                     COD_UNIDAD = 1002
                   }else{COD_UNIDAD = 1003}})

head(demanda)
```


# Necesidad de unidades nuevas
``` {r}
# Camiones grandes
grafico1 <- merge(demanda, tarifas, all.x = TRUE) %>%
  filter(COD_UNIDAD == 1001) %>%
  group_by(MES) %>%
  dplyr::summarise(capacidad_requerida = n(), 
                   capacidad_actual = (sum(EXISTENCIAS)/n())*(sum(VIAJES_MES)/n()))

highchart()%>%
  hc_add_series(data = grafico1$capacidad_requerida, 
                type = "line", color = "red", 
                name = "Capacidad requerida")%>%
  hc_add_series(data = grafico1$capacidad_actual, 
                type = "line", color = "blue", 
                name = "Capacidad actual")%>%
  hc_xAxis(categories = grafico1$MES, title = list(text = "Mes"))%>%
  hc_yAxis(title = list(text = "Viajes"))%>%
  hc_title(text = "<b>Viajes en camiones grandes<b>") %>%
  hc_subtitle(text = "<i>En varios meses se espera superar la capacidad de entrega de los camiones grandes<i>")


#Camiones pequeños
grafico2 <- merge(demanda, tarifas, all.x = TRUE) %>%
  filter(COD_UNIDAD == 1002) %>%
  group_by(MES) %>%
  dplyr::summarise(capacidad_requerida = n(), 
                   capacidad_actual = (sum(EXISTENCIAS)/n())*(sum(VIAJES_MES)/n()))

highchart()%>%
  hc_add_series(data = grafico2$capacidad_requerida, 
                type = "line", color = "red", 
                name = "Capacidad requerida")%>%
  hc_add_series(data = grafico2$capacidad_actual, 
                type = "line", color = "blue", 
                name = "Capacidad actual")%>%
  hc_xAxis(categories = grafico2$MES, title = list(text = "Mes"))%>%
  hc_yAxis(title = list(text = "Viajes"))%>%
  hc_title(text = "<b>Viajes en camiones pequeños<b>") %>%
  hc_subtitle(text = "<i><i>No se requieren nuevas unidades, sin embargo, se observa más del 50% de capacidad ociosa<i><i>")


#Paneles
grafico3 <- merge(demanda, tarifas, all.x = TRUE) %>%
  filter(COD_UNIDAD == 1003) %>%
  group_by(MES) %>%
  dplyr::summarise(capacidad_requerida = n(), 
                   capacidad_actual = (sum(EXISTENCIAS)/n())*(sum(VIAJES_MES)/n()))

highchart()%>%
  hc_add_series(data = grafico3$capacidad_requerida, 
                type = "line", color = "red", 
                name = "Capacidad requerida")%>%
  hc_add_series(data = grafico3$capacidad_actual, 
                type = "line", color = "blue", 
                name = "Capacidad actual")%>%
  hc_xAxis(categories = grafico3$MES, title = list(text = "Mes"))%>%
  hc_yAxis(title = list(text = "Viajes"))%>%
  hc_title(text = "<b>Viajes en paneles<b>") %>%
  hc_subtitle(text = "<i>No se requieren nuevas unidades<i>")
```


# Satisfacción de los clientes con las tarifas
``` {r message=FALSE, warning=FALSE}
cobros <- merge(demanda, tarifas, all.x = TRUE) %>%
  group_by(MES, CLIENTE, COD_UNIDAD, pedido) %>%
  dplyr::summarise(piloto= PILOTO_V,
                   gas = pedido*COMBUSTIBLE_U,
                   producto = pedido*PRECIO_U) %>%
  group_by(MES, CLIENTE, COD_UNIDAD, pedido) %>%
  dplyr::summarise(envio = piloto+gas,c_pedido = producto)

cobros %>%
  select(MES, pedido, envio) %>%
  group_by(MES, pedido, envio) %>%
  dplyr::summarise(tarifa_unidad = envio/pedido) %>%
  hchart('scatter',hcaes(x= tarifa_unidad, y = pedido)) %>%
  hc_title(text = "<b>Costo de envio por unidad contra el volumen del pedido <b>")

```


# 80-20 de los clientes
``` {r message=FALSE, warning=FALSE}
total <- sum(dfcantidad$unidades_totales)
clientes <- n_distinct(df$CLIENTE)

ventas_por_cliente <- df %>%
  select(CLIENTE, CANTIDAD) %>%
  group_by(CLIENTE) %>%
  dplyr::summarise(compra = sum(CANTIDAD)) %>%
  arrange(compra)%>%
  group_by(CLIENTE,compra) %>%
  dplyr::summarise(porcentaje = compra/total) %>%
  arrange(desc(compra))

clientes <- c(clientes*0.20,clientes*0.80)
ventas <- c(sum(ventas_por_cliente$porcentaje[<=3]),                        sum(ventas_por_cliente$porcentaje[ventas_por_cliente$orden>3]))

ventas_por_cliente %>% 
  select(CLIENTE, porcentaje,orden) %>%
  dplyr::summarise(p_clientes = c(clientes*0.20/clientes,clientes*0.80/clientes), 
                   ventas = c(sum(porcentaje[orden<=(clientes*0.20)]),
                              sum(porcentaje[orden>(clientes*0.20)])))

write_csv(ventas_por_cliente,'ventas_por_cliente.csv')





```
